#! /bin/sh

###########################################################################
#
# Copyright (c) 2017, Arthur N. Klassen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
###########################################################################
#
#    May you do good and not evil.
#    May you find forgiveness for yourself and forgive others.
#    May you share freely, never taking more than you give.
#
###########################################################################
#
#  SQLite is included in many Linux distros' package system but there is no
#  orderly way to download and install it onto Windows machines.
#
#  For SQLite integration, ansakLib includes this sh script which will
#  download a particular version of SQLite in its 32-bit and 64-bit libraries
#  and its 32-bit tools.
#
#  It's a VERY dumb, VERY simplistic tool. In order to use it, install your
#  favourite flavour of Cygwin on your Windows machine, create an **EMPTY**
#  directory somewhere in your file system and execute this script from within
#  it.
#
#  Before running CMake, you still have to use something like the following
#  command lines in cmd.exe, from the same sub-directory
#  cd i686
#  "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\lib.exe" /def:sqlite3.def /machine:X86 /out:sqlite3.lib
#  cd ..\x86_64
#  "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\lib.exe" /def:sqlite3.def /machine:X64 /out:sqlite3.lib
#
#  Then when executing CMake for ansakLib (in a cmd.exe prompt), defined
#  ANSAK_SQLITE_DIR= with the (non-Cygwin form of the) path where this script
#  was executed.
#
###########################################################################

wget https://sqlite.org/2017/sqlite-amalgamation-3190200.zip
mkdir include
cd include
unzip ../*.zip
cp *amalgam*/*.h .
rm -rf *amalgam*
cd ..
rm *zip

wget https://sqlite.org/2017/sqlite-dll-win32-x86-3190200.zip
mkdir i686
cd i686
unzip ../*.zip
cd ..
rm *zip

wget https://sqlite.org/2017/sqlite-dll-win64-x64-3190200.zip
mkdir x86_64
cd x86_64/
unzip ../*.zip
cd ../
rm *zip

mkdir bin
wget https://sqlite.org/2017/sqlite-tools-win32-x86-3190200.zip
cd bin
unzip ../*zip
mv sqlite-tools*/* .
rmdir sqlite-tools*
cd ..
rm *zip
